import { ImageError } from "./errors.js";

/**
 * The visual categories ("image styles") the decision engine can choose from.
 *
 * To add a new style: copy one entry, give it a new `id`, and pick an existing `layout`
 * (see overlay/layouts.js). Nothing else needs to change — see IMAGE_AUTOMATION.md §"Add a new image style".
 *
 * Fields
 *  id / label         machine id and human name
 *  layout             which text template draws the Bangla text (overlay/layouts.js)
 *  triggers           how the decision engine recognises a fitting post
 *    content_types    values of post.content_type that strongly match
 *    keywords         words in topic/hook/caption (Bangla or English, case-insensitive)
 *    goals            values of post.goal that match
 *  visual             what the background picture should show (feeds the prompt builder)
 *  text               limits for the text drawn on the image (graphemes = visible characters)
 *  requires           hard requirements — the pipeline halts with a clear reason when missing
 *  carousel_capable   true when long content may be split into slides
 */
export const CATEGORIES = [
  {
    id: "pain_solution",
    label: "Pain → Solution",
    layout: "hook_band",
    triggers: {
      content_types: ["pain_solution", "pain", "problem_solution"],
      keywords: ["ব্যথা", "যন্ত্রণা", "কষ্ট", "সমস্যা", "অস্বস্তি", "pain", "cramp", "discomfort", "স্বাভাবিক নয়"],
      goals: ["awareness", "education"],
    },
    visual: {
      mode: "photo",
      subject: "one Bangladeshi woman visibly uncomfortable but composed, recognising the problem the post is about",
      emotion: "quiet concern and discomfort — relatable, never dramatic or frightening",
      setting: "home",
      composition: "single subject positioned in the upper two-thirds, calm empty lower area",
      camera: "eye-level medium shot, 50mm lens look, shallow depth of field",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "myth_vs_fact",
    label: "Myth vs Fact",
    layout: "myth_fact",
    triggers: {
      content_types: ["myth_vs_fact", "myth", "myth_fact"],
      keywords: ["মিথ", "ভুল ধারণা", "কুসংস্কার", "সত্যি কি", "আসলে", "myth", "fact", "misconception"],
      goals: ["education", "share"],
    },
    visual: {
      mode: "photo",
      subject: "one Bangladeshi woman in a thoughtful, curious pose, as if reconsidering something she heard",
      emotion: "curious, open-minded, calm",
      setting: "home",
      composition: "subject centred in a wide frame, uncluttered background",
      camera: "eye-level medium-wide shot, soft focus background",
    },
    text: { headline_max: 40, myth_max: 70, fact_max: 90, items_max: 0 },
    requires: ["myth_fact"],
    carousel_capable: true,
  },
  {
    id: "educational_infographic",
    designed_layout: "icon_grid",
    label: "Educational infographic",
    layout: "list",
    triggers: {
      content_types: ["educational", "education", "infographic", "tips", "quick-tip"],
      keywords: ["টিপস", "উপায়", "কী করবেন", "জানুন", "tips", "ways", "how to"],
      goals: ["education", "save"],
    },
    visual: {
      mode: "photo",
      subject: "a calm Bangladeshi woman in an everyday moment related to the topic",
      emotion: "calm, confident, reassured",
      setting: "home",
      composition: "wide landscape frame, subject slightly off-centre",
      camera: "eye-level wide shot, natural light",
    },
    text: { headline_max: 50, items_max: 5, item_max: 48 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "educational_carousel",
    label: "Educational carousel",
    layout: "carousel",
    triggers: { content_types: ["carousel", "educational_carousel", "guide"], keywords: ["ধাপে ধাপে", "গাইড", "step by step", "guide"], goals: ["education", "save"] },
    visual: {
      mode: "photo",
      subject: "a Bangladeshi woman in a reassuring moment that represents the topic",
      emotion: "warm, hopeful, reassured",
      setting: "home",
      composition: "subject in the upper half, generous calm space in the lower half",
      camera: "eye-level medium shot",
    },
    text: { headline_max: 60, subtitle_max: 80, items_max: 4, item_max: 70, slides_max: 7 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "emotional_story",
    label: "Emotional / relatable story",
    layout: "hook_band",
    triggers: {
      content_types: ["emotional", "story", "emotional_support"],
      keywords: ["অনুভূতি", "মন খারাপ", "দুশ্চিন্তা", "ভয়", "একা", "আপনি একা নন", "anxiety", "feel", "alone", "emotional"],
      goals: ["connection", "engagement", "share"],
    },
    visual: {
      mode: "photo",
      subject: "an educational scenario (not a real patient): a Bangladeshi woman, or a couple, in a warm human moment related to the topic",
      emotion: "warm, empathetic, gentle hope",
      setting: "home",
      composition: "subjects in the upper two-thirds, soft natural framing",
      camera: "candid documentary-style medium shot, natural window light",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: false,
    avoid: ["implying a real patient testimonial", "melodrama or tears", "hospital emergency scenes"],
  },
  {
    id: "statistics",
    designed_layout: "stat_visual",
    label: "Statistics / data visual",
    layout: "stat",
    triggers: { content_types: ["statistic", "statistics", "data"], keywords: ["শতাংশ", "%", "প্রতি", "জন নারী", "statistic", "percent", "in every"], goals: ["awareness"] },
    visual: {
      mode: "graphic",
      subject: "an abstract, soft, minimal background with subtle organic shapes (no people)",
      emotion: "calm, credible",
      setting: "none",
      composition: "even, low-detail background suitable for large numbers on top",
      camera: "flat graphic, no camera",
    },
    text: { headline_max: 50, items_max: 0, stat_label_max: 70 },
    requires: ["verified_statistic"],
    carousel_capable: false,
  },
  {
    id: "appointment_cta",
    label: "Appointment / CTA poster",
    layout: "cta_poster",
    triggers: {
      content_types: ["appointment", "cta", "promotion", "booking"],
      keywords: ["অ্যাপয়েন্টমেন্ট", "সিরিয়াল", "চেম্বার", "যোগাযোগ করুন", "বুক করুন", "appointment", "book", "chamber", "consultation"],
      goals: ["conversion", "appointments"],
    },
    visual: {
      mode: "photo",
      subject: "a welcoming, empty, modern clinic consultation room (no people)",
      emotion: "welcoming, professional, trustworthy",
      setting: "clinic",
      composition: "interior with depth, calm upper area, uncluttered",
      camera: "eye-level wide interior shot, natural light",
    },
    text: { headline_max: 45, subtitle_max: 70, items_max: 0 },
    requires: ["contact_details"],
    carousel_capable: false,
  },
  {
    id: "doctor_trust",
    label: "Doctor face / trust post",
    layout: "doctor_quote",
    triggers: {
      content_types: ["doctor", "doctor_authority", "personal_brand", "trust", "ask_doctor"],
      keywords: ["আমি চাই", "আমার অভিজ্ঞতা", "ডাক্তার হিসেবে", "চিকিৎসক হিসেবে", "ask dr", "as a doctor", "as a gynae"],
      goals: ["trust", "authority"],
    },
    visual: {
      mode: "photo",
      subject: "a non-identifying view of a calm doctor's consultation desk: stethoscope folded neatly, notebook, a plant — no face, no person",
      emotion: "trustworthy, calm, professional",
      setting: "clinic",
      composition: "desk still-life with soft depth, calm space for a quote",
      camera: "eye-level medium shot, shallow depth of field",
    },
    text: { headline_max: 90, items_max: 0 },
    requires: ["doctor_photo_or_fallback"],
    carousel_capable: false,
  },
  {
    id: "warning_signs",
    designed_layout: "icon_grid",
    label: "Warning-sign post",
    layout: "list",
    badge: "warning",
    triggers: {
      content_types: ["warning", "awareness", "warning_signs", "red_flags"],
      keywords: ["লক্ষণ", "সতর্ক", "অবহেলা", "বিপদ", "ডাক্তার দেখান", "warning", "signs", "symptoms", "red flag"],
      goals: ["awareness", "education"],
    },
    visual: {
      mode: "photo",
      subject: "one Bangladeshi woman attentively noticing how she feels, hand resting gently where relevant",
      emotion: "alert but calm — attentive, not afraid",
      setting: "home",
      composition: "wide landscape frame, subject slightly off-centre",
      camera: "eye-level medium-wide shot",
    },
    text: { headline_max: 50, items_max: 5, item_max: 48 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "checklist",
    designed_layout: "icon_grid",
    label: "Checklist",
    layout: "list",
    badge: "check",
    triggers: { content_types: ["checklist"], keywords: ["চেকলিস্ট", "তালিকা", "মনে রাখুন", "checklist", "list"], goals: ["save"] },
    visual: {
      mode: "photo",
      subject: "a tidy flat-lay related to the topic (e.g. a notebook, a water glass, fruit) — no people",
      emotion: "organised, calm",
      setting: "home",
      composition: "top-down flat-lay with clean space",
      camera: "top-down overhead shot",
    },
    text: { headline_max: 45, items_max: 6, item_max: 42 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "comparison",
    label: "Comparison graphic",
    layout: "two_column",
    triggers: { content_types: ["comparison", "versus"], keywords: ["পার্থক্য", "বনাম", "তুলনা", "vs", "versus", "difference"], goals: ["education"] },
    visual: {
      mode: "graphic",
      subject: "a soft, minimal abstract background split gently into two calm tones (no people)",
      emotion: "clear, neutral",
      setting: "none",
      composition: "balanced left/right halves",
      camera: "flat graphic, no camera",
    },
    text: { headline_max: 45, column_title_max: 22, items_max: 4, item_max: 36 },
    requires: ["two_columns"],
    carousel_capable: false,
  },
  {
    id: "do_dont",
    label: "Do vs Don't",
    layout: "two_column",
    triggers: { content_types: ["do_dont", "dos_donts"], keywords: ["করণীয়", "বর্জনীয়", "যা করবেন", "যা করবেন না", "do's", "don'ts", "do and don't"], goals: ["education", "save"] },
    visual: {
      mode: "graphic",
      subject: "a soft, minimal abstract background split gently into two calm tones (no people)",
      emotion: "clear, friendly",
      setting: "none",
      composition: "balanced left/right halves",
      camera: "flat graphic, no camera",
    },
    text: { headline_max: 45, column_title_max: 22, items_max: 4, item_max: 36 },
    requires: ["two_columns"],
    carousel_capable: false,
  },
  {
    id: "pregnancy_timeline",
    designed_layout: "stage_columns",
    label: "Pregnancy timeline",
    layout: "timeline",
    triggers: { content_types: ["timeline", "pregnancy_timeline"], keywords: ["ত্রৈমাসিক", "সপ্তাহ", "মাসে", "trimester", "week by week", "timeline"], goals: ["education"] },
    visual: {
      mode: "photo",
      subject: "a happy, healthy pregnant Bangladeshi woman, modestly dressed, standing or sitting comfortably",
      emotion: "peaceful, expectant, happy",
      setting: "home",
      composition: "wide landscape frame, subject on one side",
      camera: "eye-level medium-wide shot",
    },
    text: { headline_max: 45, items_max: 5, item_max: 46 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "menstrual_education",
    designed_layout: "icon_grid",
    label: "Menstrual-cycle education",
    layout: "list",
    triggers: { content_types: ["menstrual", "period"], keywords: ["মাসিক", "পিরিয়ড", "ঋতুস্রাব", "চক্র", "period", "menstrual", "cycle"], goals: ["education"] },
    visual: {
      mode: "photo",
      subject: "a young Bangladeshi woman relaxing with a warm cup of tea and a small calendar or phone cycle app (screen content not visible)",
      emotion: "relaxed, informed, comfortable",
      setting: "bedroom",
      composition: "wide landscape frame, subject slightly off-centre",
      camera: "eye-level medium shot",
    },
    text: { headline_max: 50, items_max: 5, item_max: 48 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "fertility_education",
    label: "Fertility education",
    layout: "hook_band",
    triggers: { content_types: ["fertility"], keywords: ["গর্ভধারণ", "সন্তান নিতে", "উর্বর", "ডিম্বস্ফোটন", "fertility", "conceive", "ovulation", "ttc"], goals: ["education", "connection"] },
    visual: {
      mode: "photo",
      subject: "a Bangladeshi couple sitting close together, supportive and hopeful",
      emotion: "hopeful, supportive, calm",
      setting: "home",
      composition: "couple in the upper two-thirds, calm lower area",
      camera: "eye-level medium shot, warm natural light",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "pcos_awareness",
    designed_layout: "icon_grid",
    label: "PCOS awareness",
    layout: "hook_band",
    triggers: { content_types: ["pcos"], keywords: ["পিসিওএস", "পলিসিস্টিক", "pcos", "polycystic", "অনিয়মিত মাসিক"], goals: ["awareness", "education"] },
    visual: {
      mode: "photo",
      subject: "a young professional Bangladeshi woman looking thoughtful and self-aware, in a modern everyday setting",
      emotion: "thoughtful, curious, empowered",
      setting: "home",
      composition: "subject in the upper two-thirds, calm lower area",
      camera: "eye-level medium close-up",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "pregnancy_nutrition",
    designed_layout: "icon_grid",
    label: "Pregnancy nutrition",
    layout: "list",
    badge: "check",
    triggers: { content_types: ["nutrition", "pregnancy_nutrition", "diet"], keywords: ["খাবার", "পুষ্টি", "খাদ্য", "আয়রন", "food", "nutrition", "diet", "eat"], goals: ["education", "save"] },
    visual: {
      mode: "photo",
      subject: "a colourful, healthy Bangladeshi meal: rice, lentils (dal), leafy greens (shak), fish, seasonal fruit, on a simple table — no people",
      emotion: "fresh, wholesome, appetising",
      setting: "home",
      composition: "food arranged across a wide frame",
      camera: "45-degree overhead food photography, natural light",
    },
    text: { headline_max: 50, items_max: 5, item_max: 46 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "postpartum_education",
    label: "Postpartum education",
    layout: "hook_band",
    triggers: { content_types: ["postpartum"], keywords: ["প্রসবের পর", "প্রসব পরবর্তী", "সিজারের পর", "postpartum", "after birth", "after delivery"], goals: ["education", "connection"] },
    visual: {
      mode: "photo",
      subject: "a new Bangladeshi mother resting comfortably at home, a family member's supportive presence suggested",
      emotion: "tired but cared for, gentle, supported",
      setting: "bedroom",
      composition: "subject in the upper two-thirds, calm lower area",
      camera: "eye-level medium shot, soft window light",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "newborn_maternal_care",
    label: "Newborn / maternal care",
    layout: "hook_band",
    triggers: { content_types: ["newborn", "maternal_care", "breastfeeding"], keywords: ["নবজাতক", "শিশু", "বুকের দুধ", "মা ও শিশু", "newborn", "baby", "breastfeeding"], goals: ["education", "connection"] },
    visual: {
      mode: "photo",
      subject: "a Bangladeshi mother gently holding her swaddled newborn (baby fully wrapped, mother modestly dressed)",
      emotion: "tender, peaceful, loving",
      setting: "bedroom",
      composition: "mother and baby in the upper two-thirds, calm lower area",
      camera: "eye-level medium close-up, soft natural light",
    },
    text: { headline_max: 60, subtitle_max: 70, items_max: 0 },
    requires: [],
    carousel_capable: true,
    avoid: ["any nudity, including during breastfeeding", "newborn in distress"],
  },
  {
    id: "question_curiosity",
    label: "Question / curiosity",
    layout: "question",
    triggers: { content_types: ["question", "curiosity", "engagement"], keywords: ["?", "কি ", "কেন", "কীভাবে", "জানেন কি", "why", "what", "do you know"], goals: ["engagement", "curiosity"] },
    visual: {
      mode: "photo",
      subject: "a Bangladeshi woman looking thoughtfully into the distance, as if asking herself the question",
      emotion: "curious, reflective",
      setting: "home",
      composition: "subject on one side, large calm area for a big question",
      camera: "eye-level medium close-up, shallow depth of field",
    },
    text: { headline_max: 55, subtitle_max: 60, items_max: 0 },
    requires: [],
    carousel_capable: false,
  },
  {
    id: "pregnancy_tips_poster",
    label: "Pregnancy tips poster",
    layout: "list",
    designed_layout: "icon_grid",
    badge: "check",
    triggers: { content_types: ["tips", "pregnancy_tips", "tips_poster", "poster"], keywords: ["যত্ন", "টিপস", "পরামর্শ", "সুস্থ গর্ভাবস্থা", "tips", "care"], goals: ["save", "education"] },
    visual: {
      mode: "photo",
      subject: "a happy, healthy pregnant Bangladeshi woman relaxing at home",
      emotion: "calm, cared for, confident",
      setting: "home",
      composition: "wide landscape frame, subject slightly off-centre",
      camera: "eye-level medium-wide shot",
    },
    text: { headline_max: 50, items_max: 6, item_max: 40 },
    requires: [],
    carousel_capable: true,
  },
  {
    id: "condition_awareness",
    label: "Condition awareness (PCOS, pre-eclampsia, endometriosis…)",
    layout: "hook_band",
    designed_layout: "icon_grid",
    triggers: {
      content_types: ["condition", "condition_awareness", "awareness_condition", "preeclampsia"],
      keywords: ["প্রি-এক্লাম্পসিয়া", "এন্ডোমেট্রিওসিস", "থাইরয়েড", "ডায়াবেটিস", "রোগ", "condition", "preeclampsia", "endometriosis"],
      goals: ["awareness", "education"],
    },
    visual: {
      mode: "photo",
      subject: "a thoughtful Bangladeshi woman learning about her health",
      emotion: "informed, calm, empowered",
      setting: "home",
      composition: "subject in the upper two-thirds, calm lower area",
      camera: "eye-level medium shot",
    },
    text: { headline_max: 55, subtitle_max: 70, items_max: 6, item_max: 40 },
    requires: [],
    carousel_capable: true,
  },
];

const BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

export function getCategory(id) {
  const c = BY_ID.get(id);
  if (!c) throw new ImageError("UNSUPPORTED_IMAGE_TYPE", `Unknown image type "${id}". Available: ${CATEGORIES.map((x) => x.id).join(", ")}`);
  return c;
}
