// STEP 2 seed list: common, globally high-search women's-health concerns per pillar.
// Claude may pick from here or propose a fresh topic of equal relevance; recently used
// and low-performing topics are filtered out before the list reaches the prompt.
export const TOPIC_BANK = {
  Education: [
    "What a 'normal' menstrual cycle length really is",
    "What happens at a first gynaecology visit",
    "Understanding vaginal discharge: what's typical",
    "What a Pap smear / cervical screening checks for",
    "How ovulation works, simply explained",
    "What hormones actually do in the female body",
    "Perimenopause: what it is and when it can start",
    "Understanding your fertile window",
  ],
  "Myth vs Fact": [
    "PCOS myths",
    "Pregnancy food myths",
    "Period myths from around the world",
    "Contraception myths",
    "Myths about irregular periods",
    "Myths about morning sickness",
    "Fertility and age myths",
    "Myths about vaginal hygiene products",
  ],
  "Warning/Awareness": [
    "When period pain is more than 'normal' cramps",
    "Heavy menstrual bleeding: when to get checked",
    "Pregnancy warning signs to call your midwife or doctor about",
    "Bleeding between periods: when to see a doctor",
    "Signs of anaemia many women overlook",
    "Pelvic pain that shouldn't be ignored",
    "Postpartum mood changes: when it's more than baby blues",
    "Breast changes worth getting checked",
  ],
  "Pregnancy Guidance": [
    "First-trimester fatigue",
    "Managing morning sickness gently",
    "Staying active safely during pregnancy",
    "Sleep positions in later pregnancy",
    "Why antenatal check-ups matter",
    "Questions to ask at your first antenatal appointment",
    "Feeling baby's movements: what to know",
    "Preparing for the fourth trimester",
  ],
  "Hormonal/Period Health": [
    "How the 4 cycle phases affect energy and mood",
    "PMS vs PMDD: understanding the difference",
    "Why periods can become irregular",
    "Thyroid and menstrual health",
    "Stress and your cycle",
    "Insulin resistance and hormonal health",
    "Acne and hormones",
    "Tracking your cycle: what to note",
  ],
  "Emotional Support": [
    "Trying to conceive: realistic timelines",
    "Coping with pregnancy anxiety",
    "Body changes after birth: being kind to yourself",
    "Living with a chronic gynae condition",
    "Pregnancy loss: you are not alone",
    "Talking to your partner about reproductive health",
    "Feeling dismissed about your symptoms",
    "Mum guilt and self-care",
  ],
  "Preventive Tips": [
    "Daily habits that support hormonal health",
    "HPV vaccination and cervical cancer prevention",
    "Pre-conception health checklist",
    "Iron-rich foods for women",
    "Breast self-awareness routine",
    "Healthy sleep for hormonal balance",
    "Pelvic floor health for every age",
    "Bone health for women before 40",
  ],
};
